name: marker_prof
description: User Marker Profiling Library
version: 0.0.1
author: John McCutchan <john@johnmccutchan.com>
homepage: https://github.com/johnmccutchan/markerprof
dependencies:
  unittest:
    sdk: unittest
